#if !canImport(ObjectiveC)
import XCTest

extension NIOWebSocketClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NIOWebSocketClientTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NIOWebSocketClientTests.__allTests__NIOWebSocketClientTests),
    ]
}
#endif
